"""added address and phone number to user

Revision ID: f91e323ffd68
Revises: 78bfba87f901
Create Date: 2025-08-13 08:54:38.193449

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f91e323ffd68"
down_revision: Union[str, Sequence[str], None] = "78bfba87f901"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("phone_number", sa.String(), nullable=False))
    op.add_column("users", sa.Column("address", sa.String(), nullable=True))
    op.create_unique_constraint(None, "users", ["phone_number"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "address")
    op.drop_column("users", "phone_number")
    # ### end Alembic commands ###
